### ISSUE TITLE
timeout decorator issue in windows environment

### ISSUE THREAD

**Issue by mohangandhinani** [SanjayThomas/Monopoly#1]
hi could you please tell me if there is any environment requirements for the adjudicator.
I was facing this issue in windows environment looks like signals are not supported in windows environment.
Traceback (most recent call last):
  File "testcases.py", line 1535, in <module>
    test(adjudicator)
  File "testcases.py", line 101, in testcase_auction
    [winner,final_state] = adjudicator.runGame(agentOne,agentTwo,[[3,5]],None,None)
  File "D:\final sem\dsf\dsf_project\dsf-project\adjudicator.py", line 1356, in runGame
    self.conductBSTM(self.state)
  File "D:\final sem\dsf\dsf_project\dsf-project\adjudicator.py", line 534, in conductBSTM
    bstmActionAgentOne = self.runPlayerOnStateWithTimeout(self.agentOne,state)
  File "C:\Users\MOHANGANDHI\AppData\Local\Programs\Python\Python37-32\lib\site-packages\timeout_decorator\timeout_decorator.py", line 78, in new_function
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'

**Comment by SanjayThomas** [comment]
Hey Mohan,

We had tested this on Linux and Mac alone. Could I know how you are running this on Windows?
i.e., Have you installed Python as a standalone application or through Cygwin?

**Comment by mohangandhinani** [comment]
hi sanjay,
I have installed python as a standalone application and i am using git bash to execute the program which is using cygwin internally.

**Comment by SanjayThomas** [comment]
I asked because I saw this post:
https://stackoverflow.com/questions/16371421/python-signal-dont-work-even-on-cygwin

Could you try this out? Im trying this as well.

**Comment by SanjayThomas** [comment]
At the end of that post, they have said that installing the python that comes with cygwin resolved this issue.

**Comment by SanjayThomas** [comment]
Confirmed. This issue is resolved if you use python that comes with Cygwin.

**Comment by mohangandhinani** [comment]
Hi Sanjay,

Could you tell me how did you install python on cygwin.
Did you reinstall whole of cygwin or did you use any  specific commands?

*Thanks & Regards,*
*Mohan Gandhi Alapati*

**Comment by SanjayThomas** [comment]
From Cygwin installer, under the Category 'Interpreters', install 'python3' and 'python3-devel'
