### ISSUE TITLE
Reset double_counter

### ISSUE THREAD

**Issue by mohangandhinani** [SanjayThomas/Monopoly#2]
https://github.com/SanjayThomas/Monopoly/blob/b46a0c692bf4eb0b37a0a88c0c72dc57c6e40749/dice.py#L28

we were trying to understand double_counter logic.It looks like double_counter is not reset to zero and so non consecutive doubles are also getting tracked.Are we missing something?

**Comment by SanjayThomas** [comment]
We call a method 'pass_dice' at the start of every turn in runGame in adjudicator.py. This reinitializes the dice class and resets doubleCounter.

**Comment by SanjayThomas** [comment]
Will keep this issue up till filer is satisfied with the answer.

**Comment by mohangandhinani** [comment]
got it thanks you !!

**Comment by SanjayThomas** [comment]
No problem :)
