### ISSUE TITLE
TypeError: gameHistory[currentStepNumber] is undefined

### ISSUE THREAD

**Issue by ShoaibSheriff** [SanjayThomas/Monopoly#3]
Error when running React UI. 

![screenshot from 2018-11-30 20-38-28](https://user-images.githubusercontent.com/6660626/49322850-6e4a9280-f4e1-11e8-8297-083b7b602d34.png)

**Comment by varun93** [comment]
Please Start Game before clicking on the next Step. Yes we should have disabled the button before clicking next step, but that was not the focus of the project. Also you need an Agent for the UI to work.

**Comment by ShoaibSheriff** [comment]
Got this by clicking previous move. I guess technically there is no previous before 0.
 Agent and game was started. Possibly a negative index.

**Comment by varun93** [comment]
Well I agree this is a problem. But nothing serious I would say. The focus is on the adjudicator but UI is a tool only to visualize it.

**Comment by varun93** [comment]
Fixed. You can check now.

**Comment by varun93** [comment]
Closing this issue.
