### ISSUE TITLE
Adjudicator allows fractional cash.

### ISSUE THREAD

**Issue by ShoaibSheriff** [SanjayThomas/Monopoly#4]
[monopoly.log](https://github.com/SanjayThomas/Monopoly/files/2635517/monopoly.log)
![screenshot from 2018-11-30 21-24-51](https://user-images.githubusercontent.com/6660626/49323237-7d800f00-f4e6-11e8-8399-7c34c08366e6.png)

**Comment by SanjayThomas** [comment]
Fixed in the following commit:
https://github.com/SanjayThomas/Monopoly/commit/77565dd4247e0a4d38a2381ed9ff1dc539e7b356

**Comment by SanjayThomas** [comment]
This has been included as part of the testcases for auction and trade.

**Comment by ShoaibSheriff** [comment]
Great.
