### ISSUE TITLE
Agent loses when it bids too much

### ISSUE THREAD

**Issue by naummarten** [SanjayThomas/Monopoly#6]
In the spec, it says an erroneous bid should be treated as 0.

**Comment by SanjayThomas** [comment]
Since this is a query, will keep it open till filer is satisfied with the response.

**Comment by naummarten** [comment]
I don't mind keeping it this way as long as everyone is fine with it.

**Comment by SanjayThomas** [comment]
Ideally, I didn't want to change this as I still feel this is correct behaviour. However, if enough people support this, will consider this.

Closing the issue for now.
