### ISSUE TITLE
Agent in jail for more than 3 turns.

### ISSUE THREAD

**Issue by ShoaibSheriff** [SanjayThomas/Monopoly#7]
[monopoly.log](https://github.com/SanjayThomas/Monopoly/files/2636327/monopoly.log)
Check 5 turns before game ended.

**Comment by SanjayThomas** [comment]
This bug occurred when the Agent kept returning option "P" as JailDecision. The code earlier was only deducting player cash if he had enough cash causing the adjudicator to not detect bankruptcy. Have fixed this.

Awesome catch!
Thanks!

**Comment by SanjayThomas** [comment]
Fixed in https://github.com/SanjayThomas/Monopoly/commit/4138d793881569bbdd3b34eb1152b118b6f706af
