### ISSUE TITLE
Phase data when buying unowned property is tuple

### ISSUE THREAD

**Issue by naummarten** [SanjayThomas/Monopoly#8]
The "extra phase information" during the call to buyProperty on the agent contains a tuple of the form (propertyNumber, ) rather than just the property number.

**Comment by SanjayThomas** [comment]
We more or less did this for consistency's sake so that all communications from adjudicator to agent are tuples. But there is no reason to keep it this way. Will wait for 12 hours or so to see if anyone has opposition to this. Else will make this change.

**Comment by SanjayThomas** [comment]
Implemented
