### ISSUE TITLE
Player 2 wins when making payment greater than its money

### ISSUE THREAD

**Issue by naummarten** [SanjayThomas/Monopoly#9]
When player 2 lands on a space and doesn't have enough money to pay its debt, it wins the game. I suspect this is due to the following code in adjudicator.py:
```
if not result[0]:
    winner = opponent.id
    break
elif not result[1]:
    winner = currentPlayer.id
    break
```
Since the handle_payment method returns the same thing no matter whose turn it is, this produces the incorrect result.

**Comment by SanjayThomas** [comment]
Fixed in https://github.com/SanjayThomas/Monopoly/commit/bb5e2cebd3093b4c810826e4ecc7b2400730b539

Good Catch. Thanks!
